---

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt:
    name:
      - bash
      - openssl
      - libssl-dev
      - libssl-doc
    state: latest
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ db_name }}"
    encoding: "UTF-8"
    state: present

- name: Ensure user has access to the database
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    state: present

- name: GRANT ALL PRIVILEGES ON DATABASE weather TO dev
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_privs:
    db: "{{ db_name }}"
    privs: ALL
    type: database
    role: "{{ db_user }}"
