---

- name: Ansible Playbook for configuring Rasberry pi for the Weather station
  vars_files:
    - vars/main.yml

  hosts: raspberry
  roles:
    - update
    - package
    - install
  remote_user: pi
  become: yes
