---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- apt:
    name: python3-gpiozero
    state: present

- apt:
    name: libffi-dev
    state: present

- apt:
    name: python3-pip
    state: present
